### ISSUE TITLE
Extension crashes every 5-10 minutes approx

### ISSUE THREAD

**Issue by ryndshn** [apexskier/nova-typescript#91]
Extension works as expected for a while (approx 5-10 minute intervals) and then will crash. Seems like it might be related to when I save a file (I've noticed that sometimes it will crash right as I save a TS file). I can tell it crashes because the "issues" tab all the sudden doesn't show as many errors as it did before and it will stop showing inline errors. The extension works after "Restarting Server".

**To reproduce**

Use the extension for a 5-10 minute duration, you'll probably see the extension crash, possibly after you save a TS file. 

**Expected behavior**

Shouldn't crash or need to be restarted.

**Environment**

- Nova version: 1.2
- Extension version: 1.7.0
- TypeScript version: 6.13.6
- Sidebar information: It says it's running, but still displays the above behavior (isn't really working / running as expected).
- macOS version: 10.15.4 (19E287)
- NodeJS information:
  - node version: v10.15.2
  - npm version: 6.4.1
  - installation method: nvm

Please let me know if there's anything else I can do to add context to this!

**Comment by apexskier** [comment]
Nova doesn't currently provide any real way to check if the language server is still running. I'm guessing it's crashed for you.

I've confirmed that if it does crash, the [`running`](https://docs.nova.app/api-reference/language-client/#running) property doesn't report false.

As a hack, I could add some sort of "heartbeat" check to see if it's still responding to requests, but that's not a great solution. I'm going to file some feedback to Panic - at minimum we need running fixed, but I also need access to stderr and exit codes to really figure out what's going on.

**Comment by apexskier** [comment]
Nova 2 makes it possible to track crashes like this - the next release should let you report much more useful info about this (https://github.com/apexskier/nova-typescript/commit/4a7ae27107ed1d85bc3548853808824d5303faee)

**Comment by apexskier** [comment]
I'm going to close this issue, as I'm hoping Nova 2 will have improved things, and the new release should give us a lot more info.

**Comment by ryndshn** [comment]
Is it common for this extension to crash? I'm not very knowledgable on the inner-workings of typescript, but this extension continues to crash very often (probably around once every few minutes now). It does notify me of crashes now, but I'm very confused as to why it crashes as often as it does (vscode has never done this as far as i know). I'm trying to figure out if it's a problem with my environment specifically or an issue with this plugin. Is this behavior expected? 

Please let me know if i can add any additional context to this and thank you for all of your hard work on this plugin!

![image](https://user-images.githubusercontent.com/10523324/98488834-56193d00-21f9-11eb-8da7-0f00aadcd62c.png)

**Comment by apexskier** [comment]
I haven't personally experienced crashes outside of doing weird stuff with extension development. I'm guessing this is a bug in the language server that's specific to something in your codebase.

> Error: Task "apexskier.typescript" exited with a non-zero exit status: 1.

Are there any other warnings in the Extension Console? If not, I'd need to be able to locally reproduce and would need to check the language server's output (by using [this `inDevMode` functionality](https://github.com/apexskier/nova-typescript/blob/master/src/main.ts#L108-L120)), or you could run locally and grab the server logs.

**Comment by ryndshn** [comment]
i found the extension console and captured the error. it looks like the same error occurs many times, shown in the screenshot below 
![image](https://user-images.githubusercontent.com/10523324/98561249-a97da080-2276-11eb-92ab-5454f0511f6f.png)

**Comment by apexskier** [comment]
That helps a lot - it points to the source of the bug, which is not within this extension's code directly. [This is where the timeout happens](https://github.com/theia-ide/typescript-language-server/blob/cb672280c3856e6dd68620be084e6c851d80fc7f/server/src/utils.ts#L16) and [this is the command that's failing](https://github.com/theia-ide/typescript-language-server/blob/2353a405862701c6b3c5c71997b6f9c0762eb6cb/server/src/lsp-server.ts#L216).

May be caused by https://github.com/theia-ide/typescript-language-server/issues/91, may be helped by https://github.com/theia-ide/typescript-language-server/pull/168

**Comment by halfnibble** [comment]
My TypeScript server was crashing every 30 seconds or so for a while. I realized that I had dozens of files open, closed all but 10 or so, and now it's working smoothly.

Could this issue be effected when scaling the number of open TS/TSX files in Nova?

**Comment by heldr** [comment]
Issue happens for me even with a single file open, that's so frustrating.
![CleanShot 2021-01-18 at 17 10 55](https://user-images.githubusercontent.com/134727/104975761-6ba4a300-59b0-11eb-9674-d650699e5e49.png)

**Comment by apexskier** [comment]
I just published a release (v2.1.1) that includes an update to the language server that I'm hoping will fix at least @ryndshn's crash in https://github.com/apexskier/nova-typescript/issues/91#issuecomment-724087708.

**Comment by halfnibble** [comment]
Is there a way to run the extension with a node debugger attached to get a full stack trace? I'd really like to get to the bottom of this, and I'm willing to do some debugging. Also, someone mentioned an "extension console" but I don't see an interface for that in Nova.

**Comment by apexskier** [comment]
There's no way to attach a debugger to the extension directly (it run in JavaScriptCore managed by Nova, not node), but you can attach one to the underlying language server, where the crashes here are probably coming from.

Some instructions are at https://github.com/apexskier/nova-typescript/blob/main/CONTRIBUTING.md#debugging, more info on enabling the extension console is at https://library.panic.com/nova/structuring-your-project/.

**Comment by tarngerine** [comment]
i'm getting slightly different issues, but also with basically a freshly start app and only a 3-4 files open

<img width="987" alt="image" src="https://user-images.githubusercontent.com/1629901/107601790-468d0400-6bed-11eb-80a0-47a888819db2.png">

let me know what information can be helpful here? not seeing too much in the logs

**Comment by dmaglio** [comment]
same issue for me
![Screenshot 2021-03-25 at 12 38 18](https://user-images.githubusercontent.com/446573/112467228-15b0fa80-8d67-11eb-9ec8-e03ab7ebf4c4.png)

**Comment by bogdanbolchis** [comment]
Started happening today for some reason. Seems to be related to https://github.com/microsoft/TypeScript/issues/23924. Trying the workaround suggested there (symbolic link) doesn't seem to help.

```
TypeScript Language Server[15:12:49.586000] /Users/bogdanb/Library/Application Support/Nova/Extensions/apexskier.typescript/dependencyManagement/node_modules/typescript-language-server/lib/utils.js:25


TypeScript Language Server[15:12:49.586000]             this.reject(new Error(this.operation + " timeout"));


TypeScript Language Server[15:12:49.587000]                         ^


TypeScript Language Server[15:12:49.587000] 


TypeScript Language Server[15:12:49.587000] Error: compilerOptionsForInferredProjects timeout


TypeScript Language Server[15:12:49.587000]     at Timeout.<anonymous> (/Users/bogdanb/Library/Application Support/Nova/Extensions/apexskier.typescript/dependencyManagement/node_modules/typescript-language-server/lib/utils.js:25:25)


TypeScript Language Server[15:12:49.587000]     at listOnTimeout (node:internal/timers:557:17)


TypeScript Language Server[15:12:49.587000]     at processTimers (node:internal/timers:500:7)
```

**Comment by apexskier** [comment]
FYI, the next release will include this update to the underlying language server which I'm hoping will help with this issue.

https://github.com/theia-ide/typescript-language-server/pull/189

**Comment by apexskier** [comment]
Just published v2.4.0. I'm going to close this issue. If anyone keeps getting crashes that are not due to the timeouts discussed above, please open a fresh issue. Things have changed quite a bit since it was originally opened, and the problems discussed directly here should be resolved now.

Quick summary of what's happened:

1. Added detection of language server crashes (this issue helped contribute to Panic making it possible for me to do this)
2. Timeout crashes in the underlying language server.
3. Improved the ability to debug the underlying language server.

**Comment by daveyholler** [comment]
I'm running Nova 7.1 (Build 293145) with version 2.4.0 of this plugin and I'm still experiencing this crash. 

```
TypeScript Language Server stopped unexpectedly:

Error: Task “apexskier.typescript” exited with a non-zero exit status: 1.

Please report this, along with any output in the Extension Console.
```

<img width="1375" alt="image" src="https://user-images.githubusercontent.com/739960/124671501-6a860600-de6a-11eb-866d-df06160c0d00.png">

**Comment by henryboldi** [comment]
I'm still seeing this error using Nova 7.4 @apexskier

**Comment by jorisw** [comment]
Same here, with Nova 7.5

![image](https://user-images.githubusercontent.com/30017/140311675-1a64b31a-0293-4227-8070-e2c626847ea2.png)

Context: Pretty big monorepo of 5 projects, all TypeScript.
